INSERT INTO COUNTRY (ID, NAME, ABBREV) VALUES (1, 'UNITED STATES', 'US');
INSERT INTO COUNTRY (ID, NAME, ABBREV) VALUES (2, 'BRAZIL', 'BR');
INSERT INTO COUNTRY (ID, NAME, ABBREV) VALUES (3, 'CANADA', 'CA');

INSERT INTO STATE (ID, NAME, ABBREV, COUNTRY_ID) VALUES (1, 'TEXAS', 'TX', 1);
INSERT INTO STATE (ID, NAME, ABBREV, COUNTRY_ID) VALUES (2, 'CALIFORNIA', 'CA', 1);

INSERT INTO CITY (ID, NAME, STATE_ID) VALUES (1, 'AUSTIN', 1);
INSERT INTO CITY (ID, NAME, STATE_ID) VALUES (2, 'SAN FRANCISCO', 2);

INSERT INTO ADDRESS (ID, ADDRESS_LINE, ZIP_CODE, PHONE, CITY_ID) VALUES (1, '7520 EWALD FORGE', '29630', '888764123', 1);
INSERT INTO ADDRESS (ID, ADDRESS_LINE, ZIP_CODE, PHONE, CITY_ID) VALUES (2, '1267 REGGIE DAM', '57471', '987122333', 2);

INSERT INTO CUSTOMER (ID, NAME, EMAIL, ADDRESS_ID) VALUES (1, 'CRISTOBAL JEWESS', 'BLANCA@SHAD.TV', 1);
INSERT INTO CUSTOMER (ID, NAME, EMAIL, ADDRESS_ID) VALUES (2, 'ROZELLA GAYLORD', 'DILLON@KENNEDY.INFO', 2);